### ISSUE TITLE
Having trouble compiling macro

### ISSUE THREAD

**Issue by SirWindfield** [icetemple/itconfig-rs#17]
Hey there!

I have the following config:

```rust
config! {
    #![mod_name = config]

    /// The postgres database url, composed of environment variables.
    ///
    /// The default value is `postgres://kooked_admin:root@localhost:5432/kooked_main`
    DATABASE_URL < (
        "postgres://",
        POSTGRES_USERNAME => "kooked_admin",
        ":",
        POSTGRES_PASSWORD => "root",
        "@",
        POSTGRES_HOST => "localhost",
        ":",
        POSTGRES_PORT => "5432",
        "/",
        POSTGRES_DB => "kooked_main",
    ),

    /// Rockets-specific configuration values.
    ROCKET {
        ADDRESS: String => "localhost",
        PORT: u16 => 9000,
        BASE_URL: String => "/",
    }, // <-------

    /// Secret key used to create password hashes.
    ///
    /// NOTE: The default value is only used during development. If you run this in production,
    /// make sure to specify a new key
    KOOKED {
        SECRET_KEY: String => "test".repeat(8),
    }
}
```

I macro compiles fine when I leave out everything after the `<----` arrow (the comma also). I then wanted to add the secret key env variable but the compiler says that my syntax is wrong. To be honest, I really do not see any errors here.

Would be awesome if you could help me out!

P.S.: Is it possible to create better error messages than the current one? The current one just says that the syntax is wrong and I should refer to the docs. If yes, I'll try to get into proc_macros (they are still black magic for me tbh) and try to implement it :)

**Comment by SirWindfield** [comment]
Found the error. Looks like the comma right after the `ROCKET` part is wrong. Is there a reason why a command is needed after fields but not after groups? Despite the fact that the macro is just written in that way. For me at least it would make sense to have a comma after every item inside the macro.

**Comment by pleshevskiy** [comment]
Yes. you are right. I myself face this limitation :) Now I refac this macro to proc macro in #16.
and I want to make the comma an optional element after each expression

**Comment by pleshevskiy** [comment]
@SirWindfield I've released new version! Now comma is optional in the end line. Try please and leave feedback :)
